# Generated by Django 5.0.14 on 2026-09-05 17:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customer_location'),
        ('quotations', '0003_quotationline_uniq_line_quotation_product_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('comment', 'Comment'), ('counter_offer', 'Counter-offer'), ('confirmation', 'Confirmation'), ('system', 'System')], default='comment', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('counter_discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_messages', to='accounts.customer')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_messages', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_messages', to='quotations.quotation')),
                ('quotation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_messages', to='quotations.quotationline')),
            ],
            options={
                'db_table': 'negotiation_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='accounts.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='quotations.quotation')),
            ],
            options={
                'db_table': 'portal_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='negotiationmessage',
            constraint=models.CheckConstraint(check=models.Q(('author_user__isnull', False), ('author_customer__isnull', False), _negated=True), name='chk_negotiation_single_author'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['token_hash'], name='portal_sess_token_h_1c5b11_idx'),
        ),
    ]
