# Generated by Django 5.0.14 on 2026-09-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negotiationmessage',
            name='message_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('counter_offer', 'Counter-offer'), ('delivery_date_request', 'Delivery date request'), ('confirmation', 'Confirmation'), ('system', 'System')], default='comment', max_length=24),
        ),
    ]
