# Generated by Django 5.0.14 on 2026-09-05 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customer_location'),
        ('quotations', '0003_quotationline_uniq_line_quotation_product_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('stalled_deal', 'Stalled Deal (>5 days inactive)'), ('discount_anomaly', 'Discount Anomaly (>Rep Baseline)'), ('delivery_slippage', 'Delivery Slippage Risk')], max_length=32)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=16)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Escalated', 'Escalated'), ('Nudged', 'Nudged'), ('Resolved', 'Resolved')], default='Open', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=255)),
                ('nudge_count', models.PositiveIntegerField(default=0)),
                ('last_nudged_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_by_name', models.CharField(blank=True, max_length=128)),
                ('escalation_note', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='accounts.company')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='quotations.quotation')),
            ],
            options={
                'db_table': 'anomaly_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
