# Generated by Django 5.0.14 on 2026-09-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR — Indian Rupee'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('GBP', 'GBP — British Pound'), ('AED', 'AED — UAE Dirham'), ('SGD', 'SGD — Singapore Dollar')], default='INR', max_length=3),
        ),
    ]
