# Generated by Django 5.0.14 on 2026-09-05 10:36

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_score_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('required_level', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('superseded', 'Superseded')], default='pending', max_length=16)),
            ],
            options={
                'db_table': 'approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('manager', 'Sales Manager'), ('finance', 'Finance / Ops')], max_length=16)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('action', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approval_step',
                'ordering': ['sequence'],
            },
        ),
    ]
