# Generated by Django 5.0.14 on 2026-09-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='superseded_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='approvals.approvalrequest'),
        ),
    ]
