# Generated by Django 5.0.14 on 2026-09-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=16),
        ),
    ]
