# Generated by Django 5.0.14 on 2026-09-05 09:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChainRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_range_from', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_range_to', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('required_level', models.CharField(choices=[('none', 'No approval'), ('manager', 'Sales Manager'), ('manager_then_finance', 'Sales Manager → Finance')], default='manager', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_rules', to='accounts.company')),
            ],
            options={
                'db_table': 'approval_chain_rule',
                'ordering': ['discount_range_from'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('max_discount_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_tiers', to='accounts.company')),
            ],
            options={
                'db_table': 'discount_tier',
                'ordering': ['max_discount_pct'],
            },
        ),
        migrations.CreateModel(
            name='CategoryDiscountCeiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Services', 'Services'), ('Subscription', 'Subscription')], max_length=32)),
                ('max_discount_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ceilings', to='pricing_discounts.discounttier')),
            ],
            options={
                'db_table': 'category_discount_ceiling',
                'ordering': ['category'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalchainrule',
            constraint=models.CheckConstraint(check=models.Q(('discount_range_to__gt', models.F('discount_range_from'))), name='chk_approval_rule_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='discounttier',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_discount_tier_company_name'),
        ),
        migrations.AddConstraint(
            model_name='categorydiscountceiling',
            constraint=models.UniqueConstraint(fields=('discount_tier', 'category'), name='uniq_ceiling_tier_category'),
        ),
    ]
