# Generated by Django 5.0.14 on 2026-09-05 19:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customer_location'),
        ('catalog', '0001_initial'),
        ('quotations', '0003_quotationline_uniq_line_quotation_product_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsellRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_purchase_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_promoted', models.BooleanField(default=False)),
                ('min_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_rules', to='accounts.company')),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_target_rules', to='catalog.product')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_source_rules', to='catalog.product')),
            ],
            options={
                'db_table': 'upsell_rule',
                'ordering': ['-is_promoted', '-co_purchase_score'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('margin_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('Suggested', 'Suggested'), ('Added', 'Added'), ('Dismissed', 'Dismissed')], default='Suggested', max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='catalog.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='quotations.quotation')),
                ('upsell_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestions', to='upsell.upsellrule')),
            ],
            options={
                'db_table': 'suggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='upsellrule',
            constraint=models.UniqueConstraint(fields=('company', 'source_product', 'recommended_product'), name='uniq_upsell_rule_pair'),
        ),
        migrations.AddConstraint(
            model_name='suggestion',
            constraint=models.UniqueConstraint(fields=('quotation', 'upsell_rule'), name='uniq_suggestion_quotation_rule'),
        ),
    ]
