# Generated by Django 5.0.14 on 2026-09-05 14:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customer_location'),
        ('catalog', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('suggested', 'Split Suggested'), ('accepted', 'Split Accepted'), ('backordered', 'Partially Backordered'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='suggested', max_length=16)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_order', to='quotations.quotation')),
            ],
            options={
                'db_table': 'fulfillment_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackorderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('customer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorder_events', to='warehouses_fulfillment.fulfillmentorder')),
            ],
            options={
                'db_table': 'backorder_event',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('shipping_cost_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('replenishment_rule', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.company')),
            ],
            options={
                'db_table': 'warehouse',
                'ordering': ['shipping_cost_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qty_reserved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('qty_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='warehouses_fulfillment.warehouse')),
            ],
            options={
                'db_table': 'stock_level',
                'ordering': ['warehouse__shipping_cost_weight', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseSplitLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_fulfilled', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('est_shipment_count', models.PositiveSmallIntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_backorder', models.BooleanField(default=False)),
                ('consolidation_available', models.BooleanField(default=False)),
                ('is_override', models.BooleanField(default=False)),
                ('fulfillment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_lines', to='warehouses_fulfillment.fulfillmentorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='split_lines', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='split_lines', to='warehouses_fulfillment.warehouse')),
            ],
            options={
                'db_table': 'warehouse_split_line',
                'ordering': ['is_backorder', 'product__name', 'warehouse__shipping_cost_weight'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_warehouse_company_name'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='uniq_stock_warehouse_product'),
        ),
    ]
